# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            JavaScriptz
tagline:          'Everything I wish I was taught'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://royletron.github.io/javascriptz
baseurl:          '/javascriptz'

author:
  name:           'Royletron'
  url:            https://twitter.com/royletron

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/royletron/javascriptz
