# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            JavaScriptz
tagline:          'Everything I wish I was taught'
description:      'A place to share opinion on opinion, and ⛵️ loads of code'
url:              http://royletron.github.io/javascriptz
baseurl:          /javascriptz

author:
  name:           'Royletron'
  url:            https://twitter.com/royletron

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/royletron/javascriptz
